//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DungeonManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int idCart { get; set; }
        public Nullable<int> idOrder { get; set; }
        public int idCharacter { get; set; }
        public decimal Price { get; set; }
    
        public virtual Characters Characters { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
