//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DungeonManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Characters
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Characters()
        {
            this.Cart = new HashSet<Cart>();
        }
    
        public int idCharacter { get; set; }
        public string CharacterName { get; set; }
        public Nullable<int> idClass { get; set; }
        public Nullable<int> idPerks { get; set; }
        public Nullable<int> idSkills { get; set; }
        public Nullable<int> idStats { get; set; }
        public Nullable<int> idUser { get; set; }
        public decimal Price { get; set; }
        public string ImageURL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Cart { get; set; }
        public virtual Classes Classes { get; set; }
        public virtual Perks Perks { get; set; }
        public virtual Skills Skills { get; set; }
        public virtual Stats Stats { get; set; }
        public virtual Users Users { get; set; }
    }
}
